trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:

  - script: docker build -t polatefekaya/js-with-docker -f Dockerfile.dev .
    displayName: Build Dockerfile

  - script: docker run -e CI=true polatefekaya/js-with-docker npm run test
    displayName: Run Docker Container
