# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    inputs:
      command: build
      Dockerfile: Dockerfile.dev
      tags: polatefekaya/js-with-docker

  - task: Docker@2
    inputs:
      command: start
      container: polatefekaya/js-with-docker
      arguments: -e CI=true npm run test
