trigger:
  - main

pool:
  vmImage: ubuntu-latest

container: custom-named

steps:
  - task: Docker@2
    inputs:
      command: login
      containerRegistry: polat-docker

  - task: Docker@2
    inputs:
      command: build
      Dockerfile: Dockerfile.dev
      tags: polatefekaya/js-with-docker

  - script: docker run -e CI=true polatefekaya/js-with-docker npm run test
