services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=8078
    ports:
      - "8078:3000"
    volumes:
      - /app/node_modules
      - ./:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
    volumes:
      - /app/node_modules
      - ./:/app
    command: ["npm", "run", "test"]